import = [
  "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrainsMonoNerdFontMono", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFontMono", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFontMono", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNerdFontMono", style = "Bold Regular" }
size = 14.0

[window]
opacity = 1.95
startup_mode = "Maximized"
dynamic_padding = true
resize_increments = true

[colors]
transparent_background_colors = true
